export const START_REGISTER = 'START_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const START_AUTHENTICATING = 'START_AUTHENTICATING';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const GET_ERROR = 'GET_ERROR';
