export const START_REGISTER = 'START_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const START_AUTHENTICATING = 'START_AUTHENTICATING';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const GET_ERROR = 'GET_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';

export const FETCH_TASK_START = 'FETCH_TASK_START';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';

export const TODO_SAVING_START = 'TODO_SAVING_START';
export const TODO_DELETE_START = 'TODO_DELETE_START';

export const TASK_SAVING_START = 'TASK_SAVING_START';
export const TASK_DELETE_START = 'TASK_DELETE_START';

export const TASK_MARK_START = 'TASK_MARK_START';
export const TASK_MARK_SUCCESS = 'TASK_MARK_SUCCESS';
